### install pycaret

In [ ]:
!pip install --use deprecated=legacy-resolver pycaret[full]


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

ambiguous option: --use (--use-deprecated, --use-feature, --use-pep517, --user?)


In [ ]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 483.9/483.9 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 26.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.4/153.4 kB 13.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 39.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 58.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 32.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 56.8 MB/s et

### load dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from pycaret.datasets import get_data
dataset = get_data('/content/drive/MyDrive/Major Project/german_credit_2')

Unnamed: 0       status  duration           credit_history     purpose  \
0           0        <0 DM         6        critical accounts  television   
1           1      <200 DM        48  paying monthly till now  television   
2           2  no checking        12        critical accounts   education   
3           3        <0 DM        42  paying monthly till now   furniture   
4           4        <0 DM        24                    delay    car(new)   

   amount             savings employement duration  installment_rate  \
0    1169  no savings account              >7years                 4   
1    5951                <100            1-4 years                 2   
2    2096                <100            4-7 years                 2   
3    7882                <100            4-7 years                 2   
4    4870                <100            1-4 years                 3   

          personal_status_sex  ...        property  age  \
0                      single  ...     real estate   67   
1  divorced/separated/married  ...     real estate   22   
2                      single  ...     real estate   49   
3                      single  ...  life insurance   45   
4                      single  ...           other   53   

  other_installment_plans  housing number_credits       job  people_liable  \
0                    none      own              2  official              1   
1                    none      own              1  official              1   
2                    none      own              1  resident              2   
3                    none     free              1  official              2   
4                    none     free              2  official              2   

  telephone  foreign worker credit risk  
0       Yes             Yes           1  
1      None             Yes           2  
2      None             Yes           1  
3      None             Yes           1  
4      None             Yes           2  

[5 rows x 22 columns]

In [ ]:
duplicate=dataset[dataset.duplicated()]            #### duplicate values check

In [ ]:
duplicate.shape

(0, 22)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               1000 non-null   int64 
 1   status                   1000 non-null   object
 2   duration                 1000 non-null   int64 
 3   credit_history           1000 non-null   object
 4   purpose                  1000 non-null   object
 5   amount                   1000 non-null   int64 
 6   savings                  1000 non-null   object
 7   employement duration     1000 non-null   object
 8   installment_rate         1000 non-null   int64 
 9   personal_status_sex      1000 non-null   object
 10  other_debtors            1000 non-null   object
 11   present_residence       1000 non-null   int64 
 12  property                 1000 non-null   object
 13  age                      1000 non-null   int64 
 14  other_installment_plans  1000 non-null   

In [ ]:
#label encoding

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
newdata = dataset.apply(le.fit_transform)
newdata.head

<bound method NDFrame.head of      Unnamed: 0  status  duration  credit_history  purpose  amount  savings  \
0             0       0         2               1        9     142        4   
1             1       1        29               4        9     770        2   
2             2       3         8               1        4     390        2   
3             3       0        26               4        5     848        2   
4             4       0        17               2        1     734        2   
..          ...     ...       ...             ...      ...     ...      ...   
995         995       3         8               4        5     310        2   
996         996       0        21               4        2     661        2   
997         997       3         8               4        9      69        2   
998         998       0        27               4        9     332        2   
999         999       1        27               1        2     711        0   

     employement dura

In [ ]:
Fraud = newdata[newdata['credit risk']==1]
Valid = newdata[newdata['credit risk']==0]
outlier_fraction = len(Fraud)/float(len(Valid))

In [ ]:
print(outlier_fraction)
print("Fraud Cases : {}".format(len(Fraud)))
print("Valid Cases : {}".format(len(Valid)))

0.42857142857142855
Fraud Cases : 300
Valid Cases : 700


In [ ]:
import numpy as np
columns = newdata.columns.tolist()
# Filter the columns to remove data we do not want
columns = [c for c in columns if c not in ["credit risk"]]
# Store the variable we are predicting
target = "credit risk"
# Define a random state
state = np.random.RandomState(42)
X = newdata[columns]
Y = newdata[target]
X_outliers = state.uniform(low=0, high=1, size=(X.shape[0], X.shape[1]))
# Print the shapes of X & Y
print(X.shape)
print(Y.shape)

(1000, 21)
(1000,)


## **without sampling**

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(800, 21) (200, 21) (800,) (200,)


In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor


classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.0001,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.0001, novelty=True)

}


In [ ]:
from sklearn.metrics import classification_report,accuracy_score, confusion_matrix
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 59
Accuracy Score :
0.705
Classification Report :
              precision    recall  f1-score   support

           0       0.70      1.00      0.83       141
           1       0.00      0.00      0.00        59

    accuracy                           0.70       200
   macro avg       0.35      0.50      0.41       200
weighted avg       0.50      0.70      0.58       200

Confusion matrix :
[[141   0]
 [ 59   0]]
Local Outlier Factor: 59
Accuracy Score :
0.705
Classification Report :
              precision    recall  f1-score   support

           0       0.70      1.00      0.83       141
           1       0.00      0.00      0.00        59

    accuracy                           0.70       200
   macro avg       0.35      0.50      0.41       200
weighted avg       0.50      0.70      0.58       200

Confusion matrix :
[[141   0]
 [ 59   0]]


## random undersampling

In [ ]:
#RANDOM UNDERSAMPLING
from imblearn.under_sampling import RandomUnderSampler

# Perform random undersampling
rus = RandomUnderSampler(sampling_strategy=0.5, random_state=42)  # Adjust the sampling_strategy as needed
X_resampled, y_resampled = rus.fit_resample(X, Y)

print(X_resampled.shape, y_resampled.shape)

(900, 21) (900,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(720, 21) (180, 21) (720,) (180,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.001,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.01, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 53
Accuracy Score :
0.7055555555555556
Classification Report :
              precision    recall  f1-score   support

           0       0.71      1.00      0.83       127
           1       0.00      0.00      0.00        53

    accuracy                           0.71       180
   macro avg       0.35      0.50      0.41       180
weighted avg       0.50      0.71      0.58       180

Confusion matrix :
[[127   0]
 [ 53   0]]
Local Outlier Factor: 53
Accuracy Score :
0.7055555555555556
Classification Report :
              precision    recall  f1-score   support

           0       0.71      1.00      0.83       127
           1       0.00      0.00      0.00        53

    accuracy                           0.71       180
   macro avg       0.35      0.50      0.41       180
weighted avg       0.50      0.71      0.58       180

Confusion matrix :
[[127   0]
 [ 53   0]]


### ALL-KNN undersampling

In [ ]:
#all-KNN

from imblearn.under_sampling import AllKNN
from collections import Counter
allknn = AllKNN()
print('Original dataset shape %s' % Counter(Y))
X_resample, y_resample = allknn.fit_resample(X, Y)
print('Resampled dataset shape %s' % Counter(y_resample))

Original dataset shape Counter({0: 700, 1: 300})
Resampled dataset shape Counter({1: 300, 0: 161})


In [ ]:
print(X_resample.shape, y_resample.shape)

(461, 21) (461,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resample, y_resample, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(368, 21) (93, 21) (368,) (93,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.5,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.5, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 45
Accuracy Score :
0.5161290322580645
Classification Report :
              precision    recall  f1-score   support

           0       0.38      0.32      0.35        37
           1       0.59      0.64      0.62        56

    accuracy                           0.52        93
   macro avg       0.48      0.48      0.48        93
weighted avg       0.50      0.52      0.51        93

Confusion matrix :
[[12 25]
 [20 36]]
Local Outlier Factor: 42
Accuracy Score :
0.5483870967741935
Classification Report :
              precision    recall  f1-score   support

           0       0.45      0.57      0.50        37
           1       0.65      0.54      0.59        56

    accuracy                           0.55        93
   macro avg       0.55      0.55      0.54        93
weighted avg       0.57      0.55      0.55        93

Confusion matrix :
[[21 16]
 [26 30]]


## smote

In [ ]:
from imblearn.over_sampling import SMOTE
print('Original dataset shape %s' % Counter(Y))
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X, Y)
print('Resampled dataset shape %s' % Counter(y_res))

Original dataset shape Counter({0: 700, 1: 300})
Resampled dataset shape Counter({0: 700, 1: 700})


In [ ]:
print(X_res.shape, y_res.shape)

(1400, 21) (1400,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_res, y_res, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(1120, 21) (280, 21) (1120,) (280,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.01,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.01, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 132
Accuracy Score :
0.5285714285714286
Classification Report :
              precision    recall  f1-score   support

           0       0.53      0.98      0.69       149
           1       0.40      0.02      0.03       131

    accuracy                           0.53       280
   macro avg       0.47      0.50      0.36       280
weighted avg       0.47      0.53      0.38       280

Confusion matrix :
[[146   3]
 [129   2]]
Local Outlier Factor: 136
Accuracy Score :
0.5142857142857142
Classification Report :
              precision    recall  f1-score   support

           0       0.52      0.97      0.68       149
           1       0.00      0.00      0.00       131

    accuracy                           0.51       280
   macro avg       0.26      0.48      0.34       280
weighted avg       0.28      0.51      0.36       280

Confusion matrix :
[[144   5]
 [131   0]]


## SMOTE-ENN

In [ ]:
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours
from collections import Counter

sampler = SMOTEENN(random_state=42)
X_resampled, y_resampled = sampler.fit_resample(X, Y)

print(X_resampled.shape, y_resampled.shape)

(525, 21) (525,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.01,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.01, novelty=True)

}


In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 59
Accuracy Score :
0.4380952380952381
Classification Report :
              precision    recall  f1-score   support

           0       0.44      1.00      0.61        46
           1       0.00      0.00      0.00        59

    accuracy                           0.44       105
   macro avg       0.22      0.50      0.30       105
weighted avg       0.19      0.44      0.27       105

Confusion matrix :
[[46  0]
 [59  0]]
Local Outlier Factor: 59
Accuracy Score :
0.4380952380952381
Classification Report :
              precision    recall  f1-score   support

           0       0.44      0.96      0.60        46
           1       0.50      0.03      0.06        59

    accuracy                           0.44       105
   macro avg       0.47      0.50      0.33       105
weighted avg       0.47      0.44      0.30       105

Confusion matrix :
[[44  2]
 [57  2]]
