In [ ]:
!pip install --use deprecated=legacy-resolver pycaret[full]


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

ambiguous option: --use (--use-deprecated, --use-feature, --use-pep517, --user?)


In [ ]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 483.9/483.9 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.4/153.4 kB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 18.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 36.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 56.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 45.7 MB/s e

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from pycaret.datasets import get_data
dataset = get_data('/content/drive/MyDrive/creditcard')

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [ ]:
duplicate=dataset[dataset.duplicated()]            #### duplicate values check
duplicate.shape

(1081, 31)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [ ]:
#label encoding

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
newdata = dataset.apply(le.fit_transform)
newdata.head

<bound method NDFrame.head of           Time      V1      V2      V3      V4      V5      V6      V7  \
0            0   44928  120599  270851  243083  105668  211710  167150   
1            0  190308  160391  134835  182525  151841  161430  120001   
2            1   44982   28959  251918  175559   87589  253515  227985   
3            1   67135  107605  252751   68890  143700  244170  166825   
4            2   55018  212082  240745  177861   97922  181139  207795   
...        ...     ...     ...     ...     ...     ...     ...     ...   
284802  124588     581  275593     270   16342     836    1621    1093   
284803  124589   86026  122771  260722   79680  225510  239000  134669   
284804  124590  236109   96082    5048   97736  268453  261587   95134   
284805  124590  128561  182906  180282  202324  101185  221246   54711   
284806  124591  103431  107101  180358  102694  143457   84666  265094   

            V8      V9  ...     V21     V22     V23     V24     V25     V26  \
0 

In [ ]:
Fraud = newdata[newdata['Class']==1]
Valid = newdata[newdata['Class']==0]
outlier_fraction = len(Fraud)/float(len(Valid))

In [ ]:
print(outlier_fraction)
print("Fraud Cases : {}".format(len(Fraud)))
print("Valid Cases : {}".format(len(Valid)))

0.0017304750013189597
Fraud Cases : 492
Valid Cases : 284315


In [ ]:
import numpy as np
columns = newdata.columns.tolist()
# Filter the columns to remove data we do not want
columns = [c for c in columns if c not in ["Class"]]
# Store the variable we are predicting
target = "Class"
# Define a random state
state = np.random.RandomState(42)
X = newdata[columns]
Y = newdata[target]
X_outliers = state.uniform(low=0, high=1, size=(X.shape[0], X.shape[1]))
# Print the shapes of X & Y
print(X.shape)
print(Y.shape)

(284807, 30)
(284807,)


## **without sampling**

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(227845, 30) (56962, 30) (227845,) (56962,)


In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor


classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.0001,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.0001, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score, confusion_matrix
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 107
Accuracy Score :
0.998121554720691
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.26      0.05      0.09        98

    accuracy                           1.00     56962
   macro avg       0.63      0.53      0.54     56962
weighted avg       1.00      1.00      1.00     56962

Confusion matrix :
[[56850    14]
 [   93     5]]
Local Outlier Factor: 104
Accuracy Score :
0.9981742214107651
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.00      0.00      0.00        98

    accuracy                           1.00     56962
   macro avg       0.50      0.50      0.50     56962
weighted avg       1.00      1.00      1.00     56962

Confusion matrix :
[[56858     6]
 [   98     0]]


## **random undersampling**

In [ ]:
#RANDOM UNDERSAMPLING
from imblearn.under_sampling import RandomUnderSampler

# Perform random undersampling
rus = RandomUnderSampler(sampling_strategy=0.01, random_state=42)  # Adjust the sampling_strategy as needed
X_resampled, y_resampled = rus.fit_resample(X, Y)

print(X_resampled.shape, y_resampled.shape)

(49692, 30) (49692,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(39753, 30) (9939, 30) (39753,) (9939,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.0001,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.0001, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 101
Accuracy Score :
0.9898380118724218
Classification Report :
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      9839
           1       0.00      0.00      0.00       100

    accuracy                           0.99      9939
   macro avg       0.49      0.50      0.50      9939
weighted avg       0.98      0.99      0.98      9939

Confusion matrix :
[[9838    1]
 [ 100    0]]
Local Outlier Factor: 100
Accuracy Score :
0.9899386256162592
Classification Report :
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      9839
           1       0.00      0.00      0.00       100

    accuracy                           0.99      9939
   macro avg       0.49      0.50      0.50      9939
weighted avg       0.98      0.99      0.98      9939

Confusion matrix :
[[9839    0]
 [ 100    0]]


## **AllKNN undersampling**

In [ ]:
#all-KNN

from imblearn.under_sampling import AllKNN
from collections import Counter
allknn = AllKNN()
print('Original dataset shape %s' % Counter(Y))
X_resample, y_resample = allknn.fit_resample(X, Y)
print('Resampled dataset shape %s' % Counter(y_resample))

Original dataset shape Counter({0: 284315, 1: 492})
Resampled dataset shape Counter({0: 284090, 1: 492})


In [ ]:
print(X_resample.shape, y_resample.shape)

(284582, 30) (284582,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resample, y_resample, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(227665, 30) (56917, 30) (227665,) (56917,)


In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor


classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.01,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.01, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score, confusion_matrix
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 682
Accuracy Score :
0.9880176397209972
Classification Report :
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56847
           1       0.06      0.57      0.10        70

    accuracy                           0.99     56917
   macro avg       0.53      0.78      0.55     56917
weighted avg       1.00      0.99      0.99     56917

Confusion matrix :
[[56195   652]
 [   30    40]]
Local Outlier Factor: 591
Accuracy Score :
0.9896164590544125
Classification Report :
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56847
           1       0.00      0.01      0.00        70

    accuracy                           0.99     56917
   macro avg       0.50      0.50      0.50     56917
weighted avg       1.00      0.99      0.99     56917

Confusion matrix :
[[56325   522]
 [   69     1]]


## **smote**

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter
print('Original dataset shape %s' % Counter(Y))
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X, Y)
print('Resampled dataset shape %s' % Counter(y_res))

Original dataset shape Counter({0: 284315, 1: 492})
Resampled dataset shape Counter({0: 284315, 1: 284315})


In [ ]:
print(X_res.shape, y_res.shape)

(568630, 30) (568630,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_res, y_res, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(454904, 30) (113726, 30) (454904,) (113726,)


In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor

classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.001,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.001, novelty=True)

}

In [ ]:
from sklearn.metrics import classification_report,accuracy_score, confusion_matrix
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 57130
Accuracy Score :
0.4976522519036984
Classification Report :
              precision    recall  f1-score   support

           0       0.50      1.00      0.66     56750
           1       0.00      0.00      0.00     56976

    accuracy                           0.50    113726
   macro avg       0.25      0.50      0.33    113726
weighted avg       0.25      0.50      0.33    113726

Confusion matrix :
[[56596   154]
 [56976     0]]
Local Outlier Factor: 56880
Accuracy Score :
0.49985051791147145
Classification Report :
              precision    recall  f1-score   support

           0       0.50      1.00      0.67     56750
           1       0.83      0.00      0.00     56976

    accuracy                           0.50    113726
   macro avg       0.67      0.50      0.34    113726
weighted avg       0.67      0.50      0.33    113726

Confusion matrix :
[[56726    24]
 [56856   120]]


## **smote-enn**

In [ ]:
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours
from collections import Counter

sampler = SMOTEENN(random_state=42)
X_resampled, y_resampled = sampler.fit_resample(X, Y)

print(X_resampled.shape, y_resampled.shape)

(568133, 30) (568133,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
print(xtrain.shape, xtest.shape, ytrain.shape, ytest.shape)

(454506, 30) (113627, 30) (454506,) (113627,)


In [ ]:
classifiers = {
    "Isolation Forest":IsolationForest(n_estimators=100, max_samples=len(X),
                                       contamination=0.01,random_state=42, verbose=0),
    "Local Outlier Factor":LocalOutlierFactor(n_neighbors=20, algorithm='auto',
                                              leaf_size=30, metric='minkowski',
                                              p=2, metric_params=None, contamination=0.01, novelty=True)

}


In [ ]:
from sklearn.metrics import classification_report,accuracy_score
n_outliers = len(Fraud)
for i, (clf_name,clf) in enumerate(classifiers.items()):
    #Fit the data and tag outliers
    if clf_name == "Local Outlier Factor":
        clf.fit(xtrain)
        scores_prediction = clf.negative_outlier_factor_
        y_pred = clf.predict(xtest)
    #elif clf_name == "Support Vector Machine":
    #    clf.fit(X)
    #    y_pred = clf.predict(X)
    else:
        clf.fit(xtrain)
        scores_prediction = clf.decision_function(xtrain)
        y_pred = clf.predict(xtest)
    #Reshape the prediction values to 0 for Valid transactions , 1 for Fraud transactions
    y_pred[y_pred == 1] = 0
    y_pred[y_pred == -1] = 1
    n_errors = (y_pred != ytest).sum()
    # Run Classification Metrics
    print("{}: {}".format(clf_name,n_errors))
    print("Accuracy Score :")
    print(accuracy_score(ytest,y_pred))
    print("Classification Report :")
    print(classification_report(ytest,y_pred))
    print("Confusion matrix :")
    print(confusion_matrix(ytest,y_pred))

Isolation Forest: 58201
Accuracy Score :
0.4877889938130902
Classification Report :
              precision    recall  f1-score   support

           0       0.49      0.98      0.66     56649
           1       0.00      0.00      0.00     56978

    accuracy                           0.49    113627
   macro avg       0.25      0.49      0.33    113627
weighted avg       0.25      0.49      0.33    113627

Confusion matrix :
[[55426  1223]
 [56978     0]]
Local Outlier Factor: 57341
Accuracy Score :
0.4953576174676793
Classification Report :
              precision    recall  f1-score   support

           0       0.50      0.99      0.66     56649
           1       0.34      0.01      0.01     56978

    accuracy                           0.50    113627
   macro avg       0.42      0.50      0.34    113627
weighted avg       0.42      0.50      0.34    113627

Confusion matrix :
[[55901   748]
 [56593   385]]
